/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Negocio.Users.Loja;
import Negocio.Sistema;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniel
 */
public class janelaClicks extends javax.swing.JDialog {
    private Sistema sistema;
    private int i ;
    /**
     * Creates new form janelaClicks
     */
    public janelaClicks(Sistema sistema, int i) {
        
        initComponents();
    
           this.sistema = sistema;
           this.i=i;
           addTabelaLojas();
    }
    public int getI(){
        return i;
    }
    
    public void addTabelaLojas() {
        DefaultTableModel model = (DefaultTableModel) tabelaClicks.getModel();
        Object rowData[] = new Object[5];
        for (int i = 0; i < sistema.getListaUtilizadores().size(); i++) {
            if (sistema.getListaUtilizadores().todos().get(i) instanceof Loja) {

                Loja u = (Loja) sistema.getListaUtilizadores().todos().get(i);
                if(u.getClicks()<getI()){
                rowData[0] = u.getUsername();
                rowData[1] = u.getNome();
                model.addRow(rowData);
            }}
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClicks = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelaClicks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Nome"
            }
        ));
        jScrollPane1.setViewportView(tabelaClicks);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaClicks;
    // End of variables declaration//GEN-END:variables
}
