/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Negocio.Users.ListaUsers;
import Negocio.Users.Loja;
import Negocio.Sistema;
import Negocio.Users.Utilizador;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author daniel
 */
public class janelaListaLojas extends javax.swing.JDialog {

    private Sistema sistema;


    /**
     * Creates new form janelaListaLojas
     */
    public janelaListaLojas(Sistema sistema) {

        initComponents();

        this.sistema = sistema;

        addTabelaLojas();
        
       
    }

    public void addTabelaLojas() {
        DefaultTableModel model = (DefaultTableModel) tabelaLojas.getModel();
        Object rowData[] = new Object[7];
        for (int i = 0; i < sistema.getListaUtilizadores().size(); i++) {
            if (sistema.getListaUtilizadores().todos().get(i) instanceof Loja) {

                Loja u = (Loja) sistema.getListaUtilizadores().todos().get(i);
                rowData[0] = u.getUsername();
                rowData[1] = u.getPassword();
                rowData[2] = u.getNome();
                rowData[3] = u.getSubscricao();
                rowData[4] = u.getClicks();
                rowData[5] = u.getClicksRestantes();
                rowData[6] = u.getClicksUsados();
                model.addRow(rowData);
            }
        }

    }
    
    
    private void lojaMostrada() {
       if(tabelaLojas.getSelectionModel().isSelectionEmpty()){
           JOptionPane.showMessageDialog(this, "Escolha uma loja p.f.");
            tabelaLojas.requestFocus();
            return;
       }
        
        int rowIndex = tabelaLojas.getSelectedRow();
        if (rowIndex == -1) return;
        
        String username = (String) tabelaLojas.getValueAt(rowIndex, 0);
        
        try {
            sistema.getListaUtilizadores().conta(username);
            //Loja utilizador = (Loja)sistema.getListaUtilizadores().getUtilizador(username);
          //  utilizador.addClickUsados();
            
        } catch (ListaUsers.NaoVisita ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        JOptionPane.showMessageDialog(this, "Loja visitada com sucesso.");
         fechar();
        janelaListaLojas listagem = new janelaListaLojas(sistema);
        listagem.setVisible(true);
    }
    private void fechar() {
        dispose();
    }
    
    private void adicionar() {
        dispose();
        DadosLojas janela = new DadosLojas(sistema, null, this);   
        janela.setVisible(true);
    }
    
    private void editar() {
        if(tabelaLojas.getSelectionModel().isSelectionEmpty()){
           JOptionPane.showMessageDialog(this, "Escolha uma loja p.f.");
            tabelaLojas.requestFocus();
            return;
       }
        
        int rowIndex = tabelaLojas.getSelectedRow();
        if (rowIndex == -1) return;
        
        String username = (String) tabelaLojas.getValueAt(rowIndex, 0);
        
        try {
            fechar();
            Loja utilizador = (Loja)sistema.getListaUtilizadores().getUtilizador(username);
            DadosLojas janela = new DadosLojas(sistema, utilizador, this);
            janela.setVisible(true);
        } catch (ListaUsers.UtilizadorNaoExistenteException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        
    }
    
    
    public void clicks(){
        int i = Integer.parseInt(click.getText());
        
        janelaClicks clicks = new janelaClicks(sistema, i );
        clicks.setVisible(true);  
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLojas = new javax.swing.JTable();
        editar = new javax.swing.JButton();
        adicionar = new javax.swing.JButton();
        click = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        mostra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelaLojas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Nome", "Subscricao", "CLicks", "ClicksRestantes", "ClicksUsados"
            }
        ));
        jScrollPane1.setViewportView(tabelaLojas);

        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        adicionar.setText("Adicionar");
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });

        jButton1.setText("Clicks");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mostra.setText("MostraLoja");
        mostra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adicionar)
                        .addGap(18, 18, 18)
                        .addComponent(click, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(118, 118, 118)
                        .addComponent(mostra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(editar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editar)
                    .addComponent(adicionar)
                    .addComponent(click, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(mostra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
        editar();
    }//GEN-LAST:event_editarActionPerformed

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
        // TODO add your handling code here:
        adicionar();
    }//GEN-LAST:event_adicionarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clicks();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mostraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostraActionPerformed
        // TODO add your handling code here:
        lojaMostrada();
    }//GEN-LAST:event_mostraActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar;
    private javax.swing.JTextField click;
    private javax.swing.JButton editar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostra;
    private javax.swing.JTable tabelaLojas;
    // End of variables declaration//GEN-END:variables
}
