/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Negocio.Produtos.Produto;
import Negocio.Produtos.ProdutoLoja;
import Negocio.Produtos.RepositorioProduto;
import Negocio.Produtos.RepositorioProdutoLoja;
import Negocio.Sistema;
import Negocio.Users.Administrador;
import Negocio.Users.ListaUsers;
import Negocio.Users.Loja;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniel
 */
public class Procurar extends javax.swing.JDialog {
    private Sistema sistema;
    private ArrayList<ProdutoLoja> ar ;
    /**
     * Creates new form repositorioProdutoLojas
     */
    public Procurar(Sistema sistema ) {
        
        initComponents();
        
        this.sistema = sistema;
        
        
    }
    
    public void procura() throws RepositorioProdutoLoja.OProdutoNaoExiste{
        String p = texto.getText();
        try{
        this.ar  = sistema.getListaProdutoLoja().procurarProduto(p);
        }catch (RepositorioProdutoLoja.OProdutoNaoExiste ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return;

        }
        
        dispose();
        Procurar janela = new Procurar(sistema);
        janela.setVisible(true);
        
        add();
    }
    
    public void add(){
        
          DefaultTableModel model = (DefaultTableModel) tabela.getModel();
          Object rowData[] = new Object[3];
          for(int i = 0 ; i <ar.size();i++){
              
            rowData[0] = ar.get(i).getPreco();
            rowData[1] = ar.get(i).getDisponibilidade();
            rowData[2] = ar.get(i).getProduto().getNomeProduto();
            
            model.addRow(rowData);
          }
    
    }
    
    private void fechar() {
        dispose();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto = new javax.swing.JTextField();
        procurar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        procurar.setText("jButton1");
        procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(procurar)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(procurar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void procurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarActionPerformed
        try {
            // TODO add your handling code here:
            procura();
        } catch (RepositorioProdutoLoja.OProdutoNaoExiste ex) {
            Logger.getLogger(Procurar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_procurarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton procurar;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
